### ISSUE TITLE
Also capture from debug layer

### ISSUE THREAD

**Issue by lutostag** [juju/juju-crashdump#1]
https://github.com/charms/layer-debug

Should also be included. Perhaps running the debug action if there is an action available with the same signature, namely:
```
debug:
description: Collect debug data
```

**Comment by lutostag** [comment]
I have an addons branch at https://github.com/lutostag/juju-crashdump/tree/addons that enables this. Still some cleanup + tests to do.

**Comment by johnsca** [comment]
Resolved by #11
